### ISSUE TITLE
Docker Image Support

### ISSUE THREAD

**Issue by adgsenpai** [amvstrm/api#21]
To make self-hosting much easier and scalable with your updates. The docker image will be the best CI/CD way for me. I will make a contribution later or even make this my own docker image on github images repo. You will be credited all glory to you! 

You helped power animeapiv2.adgstudios.co.za for streaming. 

You broke my reverse proxy method somehow not sure how you did the detection very impressive. I'd like to personally chat to you sometime and maybe reward you. 

I am mad and also excited at the same time.

Thanks!

Will be working on fixing my stuff now. I might drop a pull request soon for the image suggestion. 

You bastard.

**Comment by adgsenpai** [comment]
I hope this message finds you well. I'm writing to clear up a misunderstanding and to express my admiration for your work.

Recently, I encountered an issue with the reverse proxy method which I initially thought was due to your software. However, upon further investigation, I realized the problem was actually caused by a rule on a third-party server we were leveraging. I apologize for any confusion this may have caused and for my hasty conclusions.

I wanted to take a moment to commend you on your exceptional work. Your contributions have been a key factor in powering animeapiv2.adgstudios.co.za for streaming, and I am thoroughly impressed with your skills and dedication.

Looking ahead, I see a great opportunity for collaboration. I'm particularly interested in enhancing the scalability and ease of self-hosting through Docker integration. I plan to contribute to this aspect soon and will ensure you receive full credit for your foundational work.

Additionally, I would value the opportunity to have a personal conversation with you. Your expertise has inspired me, and I believe there is potential for mutually beneficial collaboration. I am also considering a way to appropriately reward you for your invaluable contributions to the project.

I'm currently working on resolving my setup issues and may submit a pull request soon with a suggestion for the Docker image implementation.

Thank you once again for your remarkable work. I look forward to the possibility of working together and contributing to this exciting project.

**Comment by adgsenpai** [comment]
502 Errors from Cloudflare Due to URL Changes Impacting Service Reliability

We have recently encountered a significant issue where both of the updated URLs in our project are consistently returning a 502 error from Cloudflare. This problem is affecting the reliability and availability of our services that depend on these URLs.

### Observed Behavior
- **URL Changes:** The URLs we are using have undergone recent changes. It's unclear why these changes occurred and whether they are temporary or permanent.
- **Cloudflare 502 Error:** Both URLs are returning a 502 error, indicating that Cloudflare cannot establish a connection with our server. This error could be caused by server downtime, network issues, or configuration problems.

### Expected Behavior
The URLs should reliably connect and return the expected data without causing Cloudflare to issue 502 errors, ensuring uninterrupted service.

### Impact
- The current state with frequent 502 errors significantly affects the reliability of our services.
- Users experiencing these errors may face service interruptions.
- Our dependency on these external URLs/APIs makes our service vulnerable to external changes.

### Steps to Reproduce
1. Access the updated URLs through our service.
2. Observe the response from Cloudflare.

### Possible Causes
- Changes in the URLs and their stability.
- Misconfigurations in Cloudflare settings or server settings.
- External server or network issues.

### Recommendations
1. **Investigate URL Changes:** Determine the cause of the URL changes and stabilize them if possible.
2. **Resolve Cloudflare Issues:** Examine and rectify the Cloudflare configuration and our server settings.
3. **Explore Alternative APIs:** Consider integrating alternative APIs to ensure operational reliability.
4. **Implement Contingency Plans:** Develop strategies to handle such outages, including failover mechanisms and user communication.

### Additional Information
- Any relevant logs or error messages.
- Changes made to the system around the time the issue started.

**Comment by adgsenpai** [comment]
PS i will make your docker image still once this fucking shit is done 👍 

some work i did ... i will post it as a PR later on formally!

Dockerfile
```
# Stage 1: Build the application
FROM node:18.18 as builder

LABEL maintainer="adgsenpai"

# Create app directory
WORKDIR /usr/src/app

COPY . . 

# INSTALL 
RUN npm install

# EXPOSE 8080
EXPOSE 8080

CMD ["npm", "start"]
```

docker-compose.yml

```
version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Exposing port 8080 on the host to port 80 in the Nginx container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3
      - api4 
      - redis
    networks:
      - webnet

  api1:
    image: animeapi:latest    
    networks:
      - webnet

  api2:
    image: animeapi:latest    
    networks:
      - webnet

  api3:
    image: animeapi:latest    
    networks:
      - webnet

  api4:
    image: animeapi:latest    
    networks:
      - webnet

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - webnet
 
networks:
  webnet: {}
```

nginx.conf
```
events {}

http {
    upstream animeapi {
        server api1:8080;
        server api2:8080;
        server api3:8080;
        server api4:8080; 
    }

    server {
        listen 80;

        location / {
            proxy_pass http://animeapi;
        }
    }
}

```

Some cool fucking stuff for you as my thanks!
